import { StyleSheet } from 'react-native';
import { theme } from './theme';
import {
  BACKDROP_HEIGHT, BACKDROP_WIDTH, CARD_HEIGHT, CARD_WIDTH,
} from '../utils';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    display: 'flex',
  },
  bgDark: {
    backgroundColor: theme.colors.gray['900'],
  },
  detailsRow: {
    padding: 8,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  detailsTextHeading: {
    fontSize: 24,
    fontWeight: '600',
    textTransform: 'uppercase',
    color: theme.colors.gray['100'],
  },
  detailsText: {
    fontSize: 24,
    fontWeight: 'light',
    color: theme.colors.gray['200'],
  },
  entryContainer: {
    padding: 8,
    marginTop: 28,
    width: '90%',
    display: 'flex',
    borderRadius: 16,
    alignSelf: 'center',
    flexDirection: 'column',
    justifyContent: 'center',
  },
  entryRow: {
    display: 'flex',
    flexDirection: 'row',
    paddingHorizontal: 8,
    justifyContent: 'center',
  },
  entryText: {
    fontSize: 20,
    fontWeight: 'light',
    textAlign: 'center',
    color: theme.colors.gray['200'],
  },
  bottomTextContainer: {
    display: 'flex',
    paddingBottom: 32,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bottomText: {
    fontSize: 16,
    fontWeight: '300',
    color: theme.colors.gray['900'],
  },
  backdropContainer: {
    position: 'absolute',
    width: BACKDROP_WIDTH,
    height: BACKDROP_HEIGHT,
  },
  backdropGradient: {
    bottom: 0,
    position: 'absolute',
    width: BACKDROP_WIDTH,
    height: BACKDROP_HEIGHT,
  },
  indexContainer: {
    display: 'flex',
    flexDirection: 'row-reverse',
  },
  indexText: {
    fontSize: 64,
    paddingTop: 16,
    letterSpacing: 6,
    fontWeight: '100',
    paddingHorizontal: 16,
    color: theme.colors.gray['100'],
  },
  backdropPokemonNameContainer: {
    display: 'flex',
    alignItems: 'center',
    width: BACKDROP_WIDTH,
    height: BACKDROP_HEIGHT,
    justifyContent: 'flex-start',
    paddingTop: BACKDROP_HEIGHT / 24,
  },
  backdropPokemonName: {
    fontSize: 64,
    fontWeight: '300',
    letterSpacing: 6,
    paddingBottom: 64,
    textTransform: 'uppercase',
    maxWidth: BACKDROP_WIDTH * 0.8,
    color: theme.colors.gray['100'],
  },
  backdropPokemonImage: {
    width: BACKDROP_WIDTH,
    height: BACKDROP_WIDTH,
  },
  pokemonPressable: {
    display: 'flex',
    width: CARD_WIDTH,
    height: CARD_HEIGHT,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pokemonPressableAnimatedContainer: {
    width: 225,
    height: 225,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: CARD_WIDTH / 2,
    backgroundColor: theme.colors.gray['800'],
  },
  pokemonPressableShadow: {
    shadowColor: theme.colors.blueGray['900'],
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 0.4,
    shadowRadius: 32.00,
    elevation: 24,
  },
  pokemonPressableImageContainer: {
    width: 150,
    height: 150,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pokedexEntryButtonContainer: {
    width: '50%',
    display: 'flex',
    alignSelf: 'center',
    flexDirection: 'row',
    paddingVertical: 16,
    justifyContent: 'space-evenly',
  },
  spriteContainer: {
    padding: 8,
    width: 100,
    height: 100,
    opacity: 0.7,
    borderRadius: 50,
    marginVertical: 6,
    backgroundColor: theme.colors.gray['800'],
  },
  spriteGrid: {
    width: '80%',
    marginTop: 16,
    display: 'flex',
    borderRadius: 16,
    flexWrap: 'wrap',
    alignSelf: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  statsContainer: {
    padding: 8,
    width: '90%',
    display: 'flex',
    flexWrap: 'wrap',
    flexDirection: 'row',
    alignSelf: 'center',
    justifyContent: 'space-between',
  },
  statBarText: {
    fontSize: 16,
    paddingLeft: 4,
    marginBottom: 4,
    fontWeight: '600',
    textTransform: 'uppercase',
    color: theme.colors.gray['100'],
  },
  statBar: {
    padding: 4,
    height: 24,
    width: '100%',
    borderRadius: 8,
    borderWidth: 0.5,
    borderColor: theme.colors.gray['300'],
  },
  widthLine: {
    height: 10,
    borderWidth: 1,
    borderTopWidth: 0,
    alignItems: 'center',
    alignSelf: 'center',
    borderColor: 'rgba(255,255,255,0.6)',
  },
  widthLineText: {
    top: 15,
    fontSize: 16,
    letterSpacing: 1,
    fontWeight: '600',
    textAlign: 'center',
    alignSelf: 'center',
    position: 'absolute',
    color: theme.colors.gray['100'],
  },
  heightLine: {
    width: 10,
    borderWidth: 1,
    borderRightWidth: 0,
    borderColor: 'rgba(255,255,255,0.6)',
  },
  heightLineText: {
    top: 115,
    left: -70,
    width: 100,
    fontSize: 16,
    textAlign: 'center',
    position: 'absolute',
    fontWeight: '600',
    letterSpacing: 1,
    color: theme.colors.gray['100'],
    transform: [{ rotate: '270deg' }],
  },
});
